const Images = {
  navHome: require('../images/navigation/home.svg'),
  navHomeActive: require('../images/navigation/homeActive.png'),
  navSccount: require('../images/navigation/account.svg'),
  navAccountActive: require('../images/navigation/accountActive.svg'),
  
  bodyBg: require('../images/background.png'),
  lightBodyBg: require('../images/background.jpg'),
  topBarBg: require('../images/hader.jpg'),
  profileBg: require('../images/profile.jpeg'),
  loginLogo: require('../images/logo.png'),
  // animationLogo: require('../images/splashanimation.svg'),
  nodata: require('../images/nodata.jpg'),
  uploadIcon: require('../images/upload-icon.png'),
  facebookImg: require('../images/facebook.png'),
  paytmImg: require('../images/paytm.png'),
  atosImg: require('../images/atos.png'),
  visaImg: require('../images/visa.png'),
  shahrukkhanImg: require('../images/shahrukkhan.png'),
  flightImg: require('../images/flight.png'),
  bitmapImg: require('../images/bitmap.png'),
  amigoImg: require('../images/amigo.png'),
  gala: require('../images/gala.png'),
  win: require('../images/win.png'),
  harshitagaur: require('../images/harshitagaur.png'),
  rohitsharma: require('../images/rohitsharma.png'),
  harshita: require('../images/harshita.png'),
  enterquiz: require('../images/enterquiz.png'),
  starAnimation: require('../images/star_animation.gif'),
  amitabh: require('../images/amitabh.png'),
  amazonlogo: require('../images/amazonlogo.png'),
  onboarding: require('../images/onboarding.png'),
  arrow: require('../images/arrow.png'),
  onboardingContest: require('../images/prize.png'),
  didyoustar: require('../images/didyoustar.png'),
  srk: require('../images/srk.png'),
  harshitagaurimg: require('../images/harshitagaurimg.png'),
  militarybase: require('../images/militarybase.png'),
  nooria: require('../images/nooria.png'),
  capitalkabul: require('../images/capitalkabul.png'),
  china: require('../images/china.png'),
};

export default Images;